# Generated by Django 4.1.7 on 2023-03-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "userRandomNumber",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("userName", models.CharField(max_length=32)),
                ("userAge", models.CharField(max_length=32)),
                ("userSex", models.CharField(max_length=32)),
                ("HearLoss", models.CharField(max_length=32)),
                ("userLEar", models.CharField(max_length=32)),
                ("userLEarAid", models.CharField(max_length=32)),
                ("userREar", models.CharField(max_length=32)),
                ("userREarAid", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="UserListen",
            fields=[
                (
                    "userRandomNumber",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("userListenSex", models.CharField(max_length=32)),
                ("userListenAge", models.CharField(max_length=32)),
                ("gaussianNoise", models.CharField(max_length=32)),
            ],
        ),
    ]
