# Generated by Django 4.1.7 on 2023-03-31 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rapid7ToneDetermination", "0003_filemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filemodel",
            name="uploadTime",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 31, 2, 30, 28, 498504, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
