# Generated by Django 4.1.7 on 2023-03-31 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Rapid7ToneDetermination", "0004_alter_filemodel_uploadtime"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadFileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("path", models.FileField(upload_to="files/")),
            ],
        ),
        migrations.DeleteModel(name="FileModel",),
    ]
